name: confesso
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  go_router: ^15.1.2
  built_collection: ^5.1.1
  built_value: ^8.9.2
  cached_network_image: ^3.4.0
  camera: ^0.11.0+2
  connectivity_plus: ^5.0.2
  cryptography: ^2.7.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_analytics: ^10.8.0
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_image_compress: ^2.3.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  geocoding: ^3.0.0
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image: ^4.2.0
  image_cropper: ^7.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  location: ^7.0.0
  lottie: ^3.1.2
  mobile_scanner: ^5.2.3
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  purchases_flutter: ^8.1.4
  qr_flutter: ^4.1.0
  retack: ^0.0.6
  shared_preferences: ^2.3.2
  sign_in_with_apple: ^6.1.3
  universal_platform: ^1.1.0
  url_launcher: ^6.3.0
  uuid: ^4.5.1
  web_socket_channel: ^3.0.1
  loading_animation_widget: 1.3.0
  photo_view: ^0.15.0
  shimmer: ^3.0.0
  share_plus: ^8.0.2
  flutter_local_notifications: ^18.0.1
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
