name: confesso
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  font_awesome_flutter: ^10.8.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.4.4
  smooth_page_indicator: ^1.2.1
  lottie: ^3.1.0
  fl_chart: ^0.63.0
  flutter_slidable: ^3.1.2
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  built_value_generator: ^8.5.0
  freezed: ^2.4.5

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/animations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
